name: Release Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
    # Sequence of patterns matched against refs/tags
    tags:        
      - release*
      - v1.*


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: "./process-priority-manager/target/debug/deps/*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}